<?php
/**
 * @file
 * Authenticate UFRPE associates
 *
 * Allow user to authenticate and return user infos
 * for use in the CPA webform
 */

// Importing functions from auth_ufrpe.inc
require_once 'auth_ufrpe.inc';

/**
 * Implementation of hook_menu().
 */

function auth_ufrpe_menu()
{
  $items['admin/config/system/auth_ufrpe/settings'] = array(
    'title' => 'Configurar autenticação UFRPE',
    'description' => 'Configurar módulo de autenticação',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('auth_ufrpe_settings_form'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer site configuration'),
    'file' => 'auth_ufrpe.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_block_info()
 */

function auth_ufrpe_block_info()
{
  $blocks['auth_ufrpe'] = array(
    'info' => t('Autenticação CPA'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implementation of hook_block_views()
 */

function auth_ufrpe_block_view($delta='')
{
  $block = array();

  if ($delta == 'auth_ufrpe') {
    $block['subject'] = t('Autenticação CPA');
    $block['content'] = drupal_get_form('auth_ufrpe_form');
  }

  return $block;
}
