<?php
/**
 * @file
 * Authenticate UFRPE associates
 *
 * Allow user to authenticate and return user infos
 * for use in the CPA webform
 */

/**
 * Implementation of hook_menu().
 */

function auth_ufrpe_menu()
{
  $items['admin/autenticacao-ufrpe'] = array(
    'menu_name' => 'Management',
    'title' => 'Autenticação UFRPE',
    'page callback' => 'drupal_get_form',
    'page title' => 'Autenticação UFRPE',
    'page arguments' => array('auth_ufrpe_form'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer users site configuration'),
    'file' => 'auth_ufrpe.inc',
  );

  return $items;
}
